[2024-11-17T14:39:41.632+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_pipeline.s3_upload manual__2024-11-17T14:38:56.900690+00:00 [queued]>
[2024-11-17T14:39:41.654+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_pipeline.s3_upload manual__2024-11-17T14:38:56.900690+00:00 [queued]>
[2024-11-17T14:39:41.655+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-17T14:39:41.681+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-11-17 14:38:56.900690+00:00
[2024-11-17T14:39:41.688+0000] {standard_task_runner.py:57} INFO - Started process 48 to run task
[2024-11-17T14:39:41.697+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'currency_exchange_pipeline', 's3_upload', 'manual__2024-11-17T14:38:56.900690+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/currency_exchange_dag.py', '--cfg-path', '/tmp/tmp5hrifyof']
[2024-11-17T14:39:41.702+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask s3_upload
[2024-11-17T14:39:41.838+0000] {task_command.py:416} INFO - Running <TaskInstance: currency_exchange_pipeline.s3_upload manual__2024-11-17T14:38:56.900690+00:00 [running]> on host ca54fda2bb7e
[2024-11-17T14:39:42.047+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Azeem' AIRFLOW_CTX_DAG_ID='currency_exchange_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T14:38:56.900690+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T14:38:56.900690+00:00'
[2024-11-17T14:39:44.029+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-11-17T14:39:44.031+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-11-17T14:39:44.102+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=currency_exchange_pipeline, task_id=s3_upload, execution_date=20241117T143856, start_date=20241117T143941, end_date=20241117T143944
[2024-11-17T14:39:44.163+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task s3_upload ('NoneType' object has no attribute 'split'; 48)
[2024-11-17T14:39:44.222+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-17T14:39:44.279+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
